name: Update version based on tag

on:
  push:
    branches:
      - main
permissions: 
    contents: write

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Update pyproject with latest tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag is: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          sed -i "s/^version = .*/version = \"$TAG\"/" pyproject.toml

      - name: Commit version update
        run: |
            git config user.name "github-actions[version update]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add *pyproject.toml
            git commit -m "Automatic formatting" || exit 0
            git push

