name: Update pyproject on tag push

on:
  push:
    tags:
      - '*'

jobs:
  update-pyproject:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Extract version from tag and update pyproject.toml
      run: |
        # Extract the tag (remove 'refs/tags/' prefix)
        TAG=${GITHUB_REF#refs/tags/}
        echo $TAG

        # Use sed to update the version in pyproject.toml
        # Assumes you are using poetry and the version is in the 'tool.poetry.version' field
        sed -i "s/^version = .*/version = \"$TAG\"/" pyproject.toml

    - name: Get branch associated with the tag
      run: |
        echo $TAG
        # Get the commit hash associated with the tag
        COMMIT_HASH=$(git rev-list $TAG)

        # Find the branch that contains the tag (assumes it's pushed to a branch with this commit)
        BRANCH_NAME=$(git branch -r --contains $COMMIT_HASH | grep -v 'HEAD' | sed 's/origin\///' | head -n 1)

        echo "Branch to push: $BRANCH_NAME"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Push changes to the same branch
      run: |
        git checkout $BRANCH_NAME
        git add pyproject.toml
        git commit -m "Update pyproject.toml version to $TAG"
        git push origin $BRANCH_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
