name: Update version number

on:
  push:
    tags:
      - 'v*.*.*'
permissions: 
  contents: write

jobs:
  update-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
        uses: actions/checkout@v4
      - name: Update Version Number
        run: |
          OLD_VERSION=$(grep ^version pyproject.toml | cut -d '"' -f 2)
          OLD_VERSION="\"$OLD_VERSION\""
          echo  $OLD_VERSION
          NEW_VERSION="\"$GITHUB_REF_NAME\""
          echo $NEW_VERSION
          sed -i "s+version = $OLD_VERSION+version = $NEW_VERSION+g" pyproject.toml
      - name: Commit Changes
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git switch -c "update ver $GITHUB_REF_NAME"
          git commit -a -m "Update version number to new_version"
          git push