name: Update version from latest tag

on:
  pull_request:
permissions: 
    contents: write

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0
      - name: Update pyproject with latest tag
        run: |
          old_version=$(grep ^version pyproject.toml | cut -d '"' -f 2)
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag is: $latest_tag"
          new_version=${latest_tag#v.}
          echo "NEW_VER=$new_version" >> $GITHUB_ENV
          echo "OLD_VER=$old_version" >> $GITHUB_ENV
          sed -i "s/^version = .*/version = \"$version\"/" pyproject.toml

      - name: Commit version update
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add *pyproject.toml
            git commit -m "Version updating (${{ env.OLD_VER }} -> ${{ env.NEW_VER }})" || exit 0
            git push


